spring:
  application:
    name: batch-practice

  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.practice.batchpractice.domain
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    com.practice.batchpractice: debug